import type { Account } from "./types";

export const accountRoleLabels = {
    admin: "Quản trị viên",
    staff: "Nhân viên trung tâm",
    doctor: "Bác sĩ thú y",
    owner: "Chủ nuôi thú cưng",
} as const;

export const accountStatusLabels = {
    active: "Đang hoạt động",
    locked: "Bị khóa",
} as const;

export const mockAccounts: Account[] = [
    {
        accountId: "ACC-001",
        fullName: "Nguyễn Anh Tuấn",
        email: "tuan.nguyen@pccms.vn",
        phone: "0901234567",
        roles: ["admin", "staff"],
        status: "active",
        createdAt: "2026-03-18",
    },
    {
        accountId: "ACC-002",
        fullName: "Trần Minh Anh",
        email: "minhanh.tran@pccms.vn",
        phone: "0902234567",
        roles: ["staff"],
        status: "active",
        createdAt: "2026-03-12",
    },
    {
        accountId: "ACC-003",
        fullName: "Phạm Hoàng Nam",
        email: "hoangnam.pham@pccms.vn",
        phone: "0903234567",
        roles: ["doctor"],
        status: "active",
        createdAt: "2026-03-11",
    },
    {
        accountId: "ACC-004",
        fullName: "Lê Thu Hà",
        email: "thuha.le@pccms.vn",
        phone: "0904234567",
        roles: ["owner"],
        status: "active",
        createdAt: "2026-02-25",
    },
    {
        accountId: "ACC-005",
        fullName: "Đỗ Hoàng Minh Hiếu",
        email: "minhhieu.do@pccms.vn",
        phone: "0905234567",
        roles: ["admin"],
        status: "locked",
        createdAt: "2026-02-20",
    },
    {
        accountId: "ACC-006",
        fullName: "Hoàng Văn Thắng",
        email: "vanthang.hoang@pccms.vn",
        phone: "0906234567",
        roles: ["staff", "owner"],
        status: "active",
        createdAt: "2026-02-16",
    },
    {
        accountId: "ACC-007",
        fullName: "Trần Đình Tuệ",
        email: "dinh.tue.tran@pccms.vn",
        phone: "0907234567",
        roles: ["doctor", "staff"],
        status: "active",
        createdAt: "2026-02-13",
    },
    {
        accountId: "ACC-008",
        fullName: "Hoàng Trường Giang",
        email: "truonggiang.hoang@pccms.vn",
        phone: "0908234567",
        roles: ["owner"],
        status: "locked",
        createdAt: "2026-01-28",
    },
    {
        accountId: "ACC-009",
        fullName: "Nguyễn Thị Bảo Ngọc",
        email: "baongoc.nguyen@pccms.vn",
        phone: "0909234567",
        roles: ["owner"],
        status: "active",
        createdAt: "2026-01-21",
    },
    {
        accountId: "ACC-010",
        fullName: "Lê Quốc Huy",
        email: "quochuy.le@pccms.vn",
        phone: "0910234567",
        roles: ["staff"],
        status: "active",
        createdAt: "2026-01-18",
    },
    {
        accountId: "ACC-011",
        fullName: "Phan Thị Kim Anh",
        email: "kimanh.phan@pccms.vn",
        phone: "0911234567",
        roles: ["doctor"],
        status: "locked",
        createdAt: "2026-01-10",
    },
    {
        accountId: "ACC-012",
        fullName: "Võ Minh Khang",
        email: "minhkhang.vo@pccms.vn",
        phone: "0912234567",
        roles: ["owner", "staff"],
        status: "active",
        createdAt: "2025-12-22",
    },
    {
        accountId: "ACC-013",
        fullName: "Đặng Thu Trang",
        email: "thutrang.dang@pccms.vn",
        phone: "0913234567",
        roles: ["owner"],
        status: "active",
        createdAt: "2025-12-18",
    },
    {
        accountId: "ACC-014",
        fullName: "Bùi Gia Huy",
        email: "giahuy.bui@pccms.vn",
        phone: "0914234567",
        roles: ["staff", "doctor"],
        status: "locked",
        createdAt: "2025-12-05",
    },
];
