import type { Medicine } from "./types";

export const medicineGroups = [
    "Kháng sinh",
    "Vitamin",
    "Tiêu hóa",
    "Sát khuẩn",
    "Ký sinh trùng",
    "Khoáng chất",
    "Giảm đau",
    "Kháng viêm",
    "Điều trị mắt",
] as const;

export const medicineUnits = ["Viên", "Gói", "Lọ", "Chai", "Tuýp", "Ống"] as const;

export const stockStatusLabels = {
    inStock: "Còn hàng",
    lowStock: "Sắp hết",
    outOfStock: "Hết hàng",
} as const;

export const mockMedicines: Medicine[] = [
    {
        id: "med-001",
        code: "MED001",
        name: "Amoxicillin",
        group: "Kháng sinh",
        unit: "Viên",
        stock: 120,
        defaultUsageGuide: "Ngày 2 lần sau ăn",
        note: "Dùng cho nhiễm khuẩn nhẹ",
        isReferenced: true,
    },
    {
        id: "med-002",
        code: "MED002",
        name: "Cefalexin",
        group: "Kháng sinh",
        unit: "Viên",
        stock: 80,
        defaultUsageGuide: "Dùng theo chỉ định bác sĩ",
        note: "",
    },
    {
        id: "med-003",
        code: "MED003",
        name: "Vitamin tổng hợp",
        group: "Vitamin",
        unit: "Viên",
        stock: 45,
        defaultUsageGuide: "Ngày 1 viên sau ăn",
        note: "Bổ sung vi chất",
    },
    {
        id: "med-004",
        code: "MED004",
        name: "Thuốc nhỏ mắt",
        group: "Điều trị mắt",
        unit: "Lọ",
        stock: 20,
        defaultUsageGuide: "Nhỏ 2 lần/ngày",
        note: "",
    },
    {
        id: "med-005",
        code: "MED005",
        name: "Men tiêu hóa",
        group: "Tiêu hóa",
        unit: "Gói",
        stock: 60,
        defaultUsageGuide: "Pha với thức ăn",
        note: "",
    },
    {
        id: "med-006",
        code: "MED006",
        name: "Dung dịch sát khuẩn",
        group: "Sát khuẩn",
        unit: "Chai",
        stock: 15,
        defaultUsageGuide: "Dùng ngoài da",
        note: "Có thể gây kích ứng nhẹ",
    },
    {
        id: "med-007",
        code: "MED007",
        name: "Thuốc tẩy giun",
        group: "Ký sinh trùng",
        unit: "Viên",
        stock: 30,
        defaultUsageGuide: "Dùng theo cân nặng",
        note: "",
    },
    {
        id: "med-008",
        code: "MED008",
        name: "Canxi bổ sung",
        group: "Khoáng chất",
        unit: "Viên",
        stock: 50,
        defaultUsageGuide: "Ngày 1 viên",
        note: "",
    },
    {
        id: "med-009",
        code: "MED009",
        name: "Thuốc giảm đau",
        group: "Giảm đau",
        unit: "Viên",
        stock: 10,
        defaultUsageGuide: "Dùng sau ăn",
        note: "",
        isReferenced: true,
    },
    {
        id: "med-010",
        code: "MED010",
        name: "Thuốc chống viêm",
        group: "Kháng viêm",
        unit: "Viên",
        stock: 5,
        defaultUsageGuide: "Dùng theo chỉ định",
        note: "",
    },
    {
        id: "med-011",
        code: "MED011",
        name: "Dung dịch rửa tai",
        group: "Sát khuẩn",
        unit: "Lọ",
        stock: 7,
        defaultUsageGuide: "Nhỏ nhẹ vào tai sạch",
        note: "",
    },
    {
        id: "med-012",
        code: "MED012",
        name: "Viên bổ sung Omega-3",
        group: "Vitamin",
        unit: "Viên",
        stock: 0,
        defaultUsageGuide: "Ngày 1 viên sau ăn",
        note: "Tạm hết hàng",
    },
];
